### ISSUE TITLE
Does not detect Bootcamp

### ISSUE THREAD

**Issue by WilliamVenner** [VaasKahnGrim/MacCheck-2.0#1]
Hi,

How do I make this detect Macs running Windows via Bootcamp?

Kind Regards.

**Comment by VaasKahnGrim** [comment]
I can't do anything about macs personal Virtual Machine software for running windows. Unless I find the 2 following things first:
1. a way to send C++ binary modules to a client for gmod
2. an exploit to gain access to the host OS from inside the VM running windows.

Side note, it would be more useful to use my other addon FrenchCheck 2.0.

I hear that most mac users tend to be in france :p

**Comment by WilliamVenner** [comment]
Bootcamp isn't a virtual machine

**Comment by VaasKahnGrim** [comment]
either way vm crap ware or not, I found kinda a solution here. https://discussions.apple.com/thread/1779404

Basically at the end somebody mentioned checking the BIOS Vender and looking for "Apple", but unfortunatly that won't work since Big Brother/Facepunch doesn't want us playing with the big boy dev toys on the clientside. I'm afraid that means for the time being this addon is already as good as it can be.
